init commit
Tel3scop/brute-force-interceptor pull request #1
Opened 2024-09-13 15:32 UTC by Tel3scop

2024-09-15 16:11 UTC, POMBNK commented on internal/api/access/add_whitelist.go
> +	return &accessAPI.AddToWhitelistResponse{}, nil
наверное либо nil, либо accessAPI.AddToWhitelistResponse{}

2024-09-16 17:00 UTC, vladislavmass requested changes

2024-09-16 17:00 UTC, vladislavmass commented on internal/repository/whitelist/repository.go
> +		return false, nil
Тут явно должен быть возврат ошибки

2024-09-16 17:00 UTC, vladislavmass commented on internal/repository/whitelist/repository.go
> +		Where(sq.Expr(columnSubnet+" >>= ?", ip)).
Подскажите пожалуйста что тут имелось ввиду. Не знаком с библиотекой squirrel

2024-09-16 17:34 UTC, Tel3scop commented on internal/repository/whitelist/repository.go
> +		Where(sq.Expr(columnSubnet+" >>= ?", ip)).
squirrel - пакет билдер запросов. Из вариантов ORM или сырой sql я всегда выбирают squirrel, от него достаточно небольшая нагрузка, т.к. по сути он просто строит sql запросы из параметров
В данном случае это будет запрос что-то типа ``` SELECT 1
FROM whitelists
WHERE subnet >>= '192.168.1.1' ``` и он вернет 1, если адрес будет найден в какой-либо подсети.

2024-09-16 17:35 UTC, Tel3scop commented on internal/repository/whitelist/repository.go
> +		return false, nil
Согласен, бага. Поправлю!

2024-09-27 19:46 UTC, merged